inherit_from: .rubocop_todo.yml

require: rubocop-rails

# Specify the Ruby version your project uses
AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

# Layout rules
Layout/LineLength:
  Max: 120                # Allow lines up to 120 characters

Layout/IndentationWidth:
  Enabled: true   # Use 2 spaces for indentation
  Width: 2

Layout/TrailingWhitespace:
  Enabled: true           # Enforce no trailing whitespace

# Naming rules
Naming/VariableName:
  Enabled: true           # Enforce snake_case for variable names

Naming/MethodName:
  Enabled: true           # Enforce snake_case for method names

# Style rules
Style/FrozenStringLiteralComment:
  Enabled: false           # Require `# frozen_string_literal: true` at the top of files

Style/StringLiterals:
  EnforcedStyle: double_quotes  # Use double quotes for strings

Style/Documentation:
  Enabled: false          # Don't require documentation for every class/module
